-- The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

-- 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

-- Let us list the factors of the first seven triangle numbers:

--  1: 1
--  3: 1,3
--  6: 1,2,3,6
-- 10: 1,2,5,10
-- 15: 1,3,5,15
-- 21: 1,3,7,21
-- 28: 1,2,4,7,14,28
-- We can see that 28 is the first triangle number to have over five divisors.

-- What is the value of the first triangle number to have over five hundred divisors?

tri :: Int -> Int
tri n = sum [1..n]

numOfDivisors :: Int -> Int
numOfDivisors 1 = 1
numOfDivisors n = do
    let divisors = (*2) . length $ filter (\x -> n `mod` x == 0) [1 .. round $ sqrt $ fromIntegral n]
    if ((round $ sqrt $ fromIntegral n) ^ 2 == n) then divisors + 1 else divisors

ans = head $ filter (\x -> numOfDivisors x > 500) $ map tri [1..]

main :: IO ()
main = putStrLn $ show ans
